export enum AppErrorType {
  ALREADY_OPEN_ACCOUNT = 'ALREADY_OPEN_ACCOUNT',
  NOTFOUND_ORIGIN_ACCOUNT = 'NOT_FOUND_ACCOUNT',
  NOTFOUND_DESTINY_ACCOUNT = 'NOT_FOUND_DESTINY_ACCOUNT',
  NON_SUFFICIENT_FUNDS = 'NON_SUFFICIENT_FUNDS',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
}
