services:
  ipkisstest-api:
    container_name: ipkisstest-api
    volumes:
      - .:/app
    build:
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT:-8080}
      - NODE_ENV=production
      - SIMPLE_LOGGER=${SIMPLE_LOGGER:-true}
      - TRACE_URL=${TRACE_URL:-http://0.0.0.0:4318/v1/traces}
    ports:
      - ${PORT:-8080}:${PORT:-8080}
