services:
  ipkisstest-api:
    container_name: ipkisstest-api-dev
    volumes:
      - .:/app
    build:
      dockerfile: Dockerfile.dev
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=development
      - SIMPLE_LOGGER=${SIMPLE_LOGGER:-false}
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    depends_on:
      - tracing
    restart: on-failure

  dozzle:
    container_name: ipkisstest-dozzle-dev
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

  tracing:
    container_name: ipkisstest-jaeger-dev
    image: jaegertracing/all-in-one:latest
    volumes:
      - jaeger-data-dev:/tmp
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

volumes:
  jaeger-data-dev:
